/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include <ctype.h> /* toupper() */
#include <string.h>
#include "linkbus.h"
#include "linkbus_rx_bounds.h"
#include "serialbus.h"
#include "usart_basic.h"
#include "morse.h"

void serial_Rx(uint8_t rx_char);
void serial_Tx(uint8_t rx_char);
void linkbus_Rx(uint8_t rx_char);
void linkbus_Tx(uint8_t rx_char);

extern USART_Number_t g_serialbus_usart_number;
extern USART_Number_t g_linkbus_usart_number;

ISR(USART0_RXC_vect)
{
	uint8_t rx_char = USART0_get_data();
	
	if(g_linkbus_usart_number == USART_0)
	{
		linkbus_Rx(rx_char);
	}
	
	if(g_serialbus_usart_number == USART_0)
	{
		serial_Rx(rx_char);
	}
}

ISR(USART4_RXC_vect)
{
	uint8_t rx_char = USART4_get_data();
	
	if(g_linkbus_usart_number == USART_4)
	{
		linkbus_Rx(rx_char);
	}
	
	if(g_serialbus_usart_number == USART_4)
	{
		serial_Rx(rx_char);
	}
}

void serial_Rx(uint8_t rx_char)
{
}

/**

*/
ISR(USART0_DRE_vect)
{
	if(g_linkbus_usart_number == USART_0)
	{
		static LinkbusTxBuffer* buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullLBTxBuffer();
		}

		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART0.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullLBTxBuffer();
			if(!buff)
			{
				linkbus_end_tx();
			}
		}
	}
	
	if(g_serialbus_usart_number == USART_0)
	{
		static SerialbusTxBuffer* buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullSBTxBuffer();
		}

		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART0.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullSBTxBuffer();
			if(!buff)
			{
				serialbus_end_tx();
			}
		}
	}
}


/**

*/
ISR(USART4_DRE_vect)
{
	if(g_linkbus_usart_number == USART_4)
	{
		static LinkbusTxBuffer* buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullLBTxBuffer();
		}

		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART4.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullLBTxBuffer();
			if(!buff)
			{
				linkbus_end_tx();
			}
		}
	}
	
	if(g_serialbus_usart_number == USART_4)
	{
		static SerialbusTxBuffer* buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullSBTxBuffer();
		}

		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART4.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullSBTxBuffer();
			if(!buff)
			{
				serialbus_end_tx();
			}
		}
	}
}


/**

*/
ISR(USART1_RXC_vect)
{
	uint8_t rx_char = USART1_get_data();	
	
	if(g_linkbus_usart_number == USART_1)
	{
		linkbus_Rx(rx_char);
	}
	
	if(g_serialbus_usart_number == USART_1)
	{
		serial_Rx(rx_char);
	}
}

void linkbus_Rx(uint8_t rx_char)
{
	static LinkbusRxBuffer* buff = NULL;
	static uint8_t charIndex = 0;
	static uint8_t field_index = 0;
	static uint8_t field_len = 0;
	static uint8_t id_len = 0;
	static uint32_t tempMsg_ID = 0;
	static bool receiving_msg = false;
	static bool escapeNext = false;

	if(!buff)
	{
		buff = nextEmptyLBRxBuffer();
	}

	if(buff)
	{
		rx_char = toupper(rx_char);
		
		if(!escapeNext && (rx_char == '\\'))
		{
			escapeNext = true;
		}
		else if(!escapeNext && ((rx_char == '$') || (rx_char == '!')))    /* start of new message = $ */
		{
			charIndex = 0;
			buff->type = (rx_char == '!') ? LINKBUS_MSG_REPLY : LINKBUS_MSG_COMMAND;
			field_len = 0;
			id_len = 0;
			tempMsg_ID = 0;
			receiving_msg = true;

			/* Empty the field buffers */
			for(field_index = 0; field_index < LINKBUS_MAX_MSG_NUMBER_OF_FIELDS; field_index++)
			{
				buff->fields[field_index][0] = '\0';
			}

			field_index = 0;
		}
		else if(receiving_msg)
		{
			if(!escapeNext && ((rx_char == ',') || (rx_char == ';') || (rx_char == '?')))   /* new field = ,; end of message = ; */
			{
				bool malformed = false;
				if(field_index > 0)
				{
					if(linkbus_rx_field_can_terminate(field_index, field_len,
						LINKBUS_MAX_MSG_NUMBER_OF_FIELDS, LINKBUS_MAX_MSG_FIELD_LENGTH))
					{
						buff->fields[field_index - 1][field_len] = 0;
					}
					else
					{
						malformed = true;
					}
				}

				if((rx_char == ',') &&
					!linkbus_rx_can_start_next_field(field_index, LINKBUS_MAX_MSG_NUMBER_OF_FIELDS))
				{
					malformed = true;
				}

				if(malformed)
				{
					buff->id = LB_MESSAGE_EMPTY;
					receiving_msg = false;
					buff = NULL;
				}
				else
				{
					field_index++;
					field_len = 0;

					if(rx_char == ';')
					{
						if(charIndex > LINKBUS_MIN_MSG_LENGTH)
						{
							buff->id = (LBMessageID)tempMsg_ID;
						}
						receiving_msg = false;
					}
					else if(rx_char == '?')
					{
						buff->type = LINKBUS_MSG_QUERY;
						if(charIndex >= LINKBUS_MIN_MSG_LENGTH)
						{
							buff->id = (LBMessageID)tempMsg_ID;
						}
						receiving_msg = false;
					}

					if(!receiving_msg)
					{
						buff = 0;
					}
				}
			}
			else
			{
				if(field_index == 0)    /* message ID received */
				{
					if(linkbus_rx_id_can_append(id_len, LINKBUS_MAX_MSG_ID_LENGTH))
					{
						tempMsg_ID = tempMsg_ID * 10 + rx_char;
						id_len++;
					}
					else
					{
						buff->id = LB_MESSAGE_EMPTY;
						receiving_msg = false;
						buff = NULL;
					}
				}
				else
				{
					if(linkbus_rx_field_can_append(field_index, field_len,
						LINKBUS_MAX_MSG_NUMBER_OF_FIELDS, LINKBUS_MAX_MSG_FIELD_LENGTH))
					{
						buff->fields[field_index - 1][field_len++] = rx_char;
					}
					else
					{
						buff->id = LB_MESSAGE_EMPTY;
						receiving_msg = false;
						buff = NULL;
					}
				}
				
				escapeNext = false;
			}
		}
		else if(rx_char == 0x0D)    /* Carriage return resets any message in progress */
		{
			buff->id = LB_MESSAGE_EMPTY;
			charIndex = LINKBUS_MAX_MSG_LENGTH;
			field_len = 0;
			id_len = 0;
			tempMsg_ID = 0;
			field_index = 0;
			buff = NULL;
		}

		if(!escapeNext)
		{
			if(++charIndex >= LINKBUS_MAX_MSG_LENGTH)
			{
				receiving_msg = false;
				charIndex = 0;
			}
		}
	}
}


/**

*/
ISR(USART1_DRE_vect)
{
	if(g_serialbus_usart_number == USART_1)
	{
		static SerialbusTxBuffer* buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullSBTxBuffer();
		}

		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART1.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullSBTxBuffer();
			if(!buff)
			{
				serialbus_end_tx();
			}
		}
	}
	
	if(g_linkbus_usart_number == USART_1)
	{
		static LinkbusTxBuffer* buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullLBTxBuffer();
		}

		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART1.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullLBTxBuffer();
			if(!buff)
			{
				linkbus_end_tx();
			}
		}
	}
}
