/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include <ctype.h> /* toupper() */
#include "include/linkbus.h"
#include "include/usart_basic.h"
#include "include/morse.h"

ISR(TCA0_OVF_vect)
{
	/* Insert your TCA overflow interrupt handling code */
//	LED_toggle_level();

	/* The interrupt flag has to be cleared manually */
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;
}

ISR(TCB1_INT_vect)
{
    if(TCB1.INTFLAGS & TCB_CAPT_bm)
    {
        TCB1.INTFLAGS = TCB_CAPT_bm;
    }
}

ISR(TCB2_INT_vect)
{
	if(TCB2.INTFLAGS & TCB_CAPT_bm)
    {
        TCB2.INTFLAGS = TCB_CAPT_bm;
    }
}


/**
One-second counter based on CPU clock.
*/
ISR(TCB3_INT_vect)
{
 	static uint16_t cnt = 0;
	
    /* Insert your TCB interrupt handling code */
    /**
     * The interrupt flag is cleared by writing 1 to it, or when the Capture register
     * is read in Capture mode
     */

    if(TCB3.INTFLAGS & TCB_CAPT_bm)
    {
		if(cnt++ == 299)
		{
			cnt = 0;
			LED_toggle_level();
		}

        TCB3.INTFLAGS = TCB_CAPT_bm;
    }
}

/**

*/
ISR(USART1_RXC_vect)
{
	static LinkbusRxBuffer* buff = NULL;
	static uint8_t charIndex = 0;
	static uint8_t field_index = 0;
	static uint8_t field_len = 0;
	static uint32_t msg_ID = 0;
	static BOOL receiving_msg = FALSE;
	uint8_t rx_char;

	rx_char = USART1_get_data();

	if(!buff)
	{
		buff = nextEmptyRxBuffer();
	}

	if(buff)
	{
		rx_char = toupper(rx_char);
//		SMCR = 0x00;                                /* exit power-down mode */

		if((rx_char == '$') || (rx_char == '!'))    /* start of new message = $ */
		{
			charIndex = 0;
			buff->type = (rx_char == '!') ? LINKBUS_MSG_REPLY : LINKBUS_MSG_COMMAND;
			field_len = 0;
			msg_ID = LINKBUS_MSG_UNKNOWN;
			receiving_msg = TRUE;

			/* Empty the field buffers */
			for(field_index = 0; field_index < LINKBUS_MAX_MSG_NUMBER_OF_FIELDS; field_index++)
			{
				buff->fields[field_index][0] = '\0';
			}

			field_index = 0;
		}
		else if(receiving_msg)
		{
			if((rx_char == ',') || (rx_char == ';') || (rx_char == '?'))    /* new field = ,; end of message = ; */
			{
				/* if(field_index == 0) // message ID received */
				if(field_index > 0)
				{
					buff->fields[field_index - 1][field_len] = 0;
				}

				field_index++;
				field_len = 0;

				if(rx_char == ';')
				{
					if(charIndex > LINKBUS_MIN_MSG_LENGTH)
					{
						buff->id = (LBMessageID)msg_ID;
					}
					receiving_msg = FALSE;
				}
				else if(rx_char == '?')
				{
					buff->type = LINKBUS_MSG_QUERY;
					if(charIndex > LINKBUS_MIN_MSG_LENGTH)
					{
						buff->id = msg_ID;
					}
					receiving_msg = FALSE;
				}

				if(!receiving_msg)
				{
					buff = 0;
				}
			}
			else
			{
				if(field_index == 0)    /* message ID received */
				{
					msg_ID = msg_ID * 10 + rx_char;
				}
				else
				{
					buff->fields[field_index - 1][field_len++] = rx_char;
				}
			}
		}
		else if(rx_char == 0x0D)    /* Handle carriage return */
		{
			buff->id = LINKBUS_MSG_UNKNOWN;
			charIndex = LINKBUS_MAX_MSG_LENGTH;
			field_len = 0;
			msg_ID = LINKBUS_MSG_UNKNOWN;
			field_index = 0;
			buff = NULL;
		}

		if(++charIndex >= LINKBUS_MAX_MSG_LENGTH)
		{
			receiving_msg = FALSE;
			charIndex = 0;
		}
	}
}


/**

*/
ISR(USART1_DRE_vect)
{
	static LinkbusTxBuffer* buff = 0;
	static uint8_t charIndex = 0;

	if(!buff)
	{
		buff = nextFullTxBuffer();
	}

	if((*buff)[charIndex])
	{
		/* Put data into buffer, sends the data */
		USART1.TXDATAL = (*buff)[charIndex++];
	}
	else
	{
		charIndex = 0;
		(*buff)[0] = '\0';
		buff = nextFullTxBuffer();
		if(!buff)
		{
			linkbus_end_tx();
		}
	}
}
